<?php

/**
 * BaseIStoreOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $credit_card_id
 * @property integer $address_id
 * @property date $date
 * @property integer $payment
 * @property boolean $is_validated
 * @property IStoreAddress $IStoreAddress
 * @property Doctrine_Collection $order
 * 
 * @method integer             getCreditCardId()   Returns the current record's "credit_card_id" value
 * @method integer             getAddressId()      Returns the current record's "address_id" value
 * @method date                getDate()           Returns the current record's "date" value
 * @method integer             getPayment()        Returns the current record's "payment" value
 * @method boolean             getIsValidated()    Returns the current record's "is_validated" value
 * @method IStoreAddress       getIStoreAddress()  Returns the current record's "IStoreAddress" value
 * @method Doctrine_Collection getOrder()          Returns the current record's "order" collection
 * @method IStoreOrder         setCreditCardId()   Sets the current record's "credit_card_id" value
 * @method IStoreOrder         setAddressId()      Sets the current record's "address_id" value
 * @method IStoreOrder         setDate()           Sets the current record's "date" value
 * @method IStoreOrder         setPayment()        Sets the current record's "payment" value
 * @method IStoreOrder         setIsValidated()    Sets the current record's "is_validated" value
 * @method IStoreOrder         setIStoreAddress()  Sets the current record's "IStoreAddress" value
 * @method IStoreOrder         setOrder()          Sets the current record's "order" collection
 * 
 * @package    i-store
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIStoreOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i_store_order');
        $this->hasColumn('credit_card_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('payment', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_validated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IStoreAddress', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasMany('IStoreOrderLine as order', array(
             'local' => 'id',
             'foreign' => 'order_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}