<?php

/**
 * BaseIStoreAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $customer_id
 * @property string $street
 * @property string $state
 * @property string $city
 * @property integer $zipcode
 * @property string $country
 * @property IStoreCustomer $IStoreCustomer
 * 
 * @method integer        getCustomerId()     Returns the current record's "customer_id" value
 * @method string         getStreet()         Returns the current record's "street" value
 * @method string         getState()          Returns the current record's "state" value
 * @method string         getCity()           Returns the current record's "city" value
 * @method integer        getZipcode()        Returns the current record's "zipcode" value
 * @method string         getCountry()        Returns the current record's "country" value
 * @method IStoreCustomer getIStoreCustomer() Returns the current record's "IStoreCustomer" value
 * @method IStoreAddress  setCustomerId()     Sets the current record's "customer_id" value
 * @method IStoreAddress  setStreet()         Sets the current record's "street" value
 * @method IStoreAddress  setState()          Sets the current record's "state" value
 * @method IStoreAddress  setCity()           Sets the current record's "city" value
 * @method IStoreAddress  setZipcode()        Sets the current record's "zipcode" value
 * @method IStoreAddress  setCountry()        Sets the current record's "country" value
 * @method IStoreAddress  setIStoreCustomer() Sets the current record's "IStoreCustomer" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIStoreAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i_store_address');
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('zipcode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IStoreCustomer', array(
             'local' => 'customer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}