generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Gestion des compte client
        layout:   stacked
        display:  [ id, username, email_address, last_name, first_name, last_login, is_active]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~


