generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Nouveau
      fields:
        username:       { label: login }
        email_address:  { label: Adresse e-mail }
        last_name:      { label: Nom }
        first_name:     { label: Prénom }
        last_login:     { label: Dernière connexion }
        is_active:      { label: Activé }
      list:
        title:    Gestion des compte client
        layout:   tabular
        display:  [ id, username, email_address, last_name, first_name, last_login, is_active]
        object_actions:
          activate:
            label: activer
          deactivate:
            label: désactiver
          _delete:
            label: Supprimer
          _edit:
            label: Modifier
        batch_actions:
          activate:
            label: activer
          deactivate:
            label: désactiver
          delete:
            label: Supprimer
      filter:  ~
      form:    ~
      edit:
        title: Modifier l'article "%%username%%"
        actions:
          _list:   { label: revenir à la liste }
          _save:   { label: enregistrer }
      new:
        title: Ajouter un nouveau article
        actions:
          _list:   { label: revenir à la liste }
          _save:   { label: enregistrer }
          _save_and_add:  { label: enregistrer et ajouter }


