<?php

/**
 * IStoreAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreAddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreAddress');
    }

    /**
     *  Retourne la requete doctrine permettant de récupérer
     *      la liste des addresses des client. La requete peut
     *      être ajusté en fonction du besoin. 
     *
     * @param Doctrine_Query $q  requete Doctrine à combiner
     * @return Doctrine_Query  nouvelle requête Doctrine résultant des
     *      requêtes combinés
     */
    public function addAddressesQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
          $q = Doctrine_Query::create()
            ->from('IStoreAddress i');
        }

        $alias = $q->getRootAlias();

        return $q;
    }
}