<?php

/**
 * IStoreCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreCustomerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreCustomer');
    }
}