<?php

/**
 * IStoreCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    i-store
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IStoreCategory extends BaseIStoreCategory
{
    /**
     *  Retourne les sous-catégories associées à la catégorie
     *
     * @return Doctrine_Collection  collection d'objet doctrine
     */
    public function getChildCategories()
    {
        $q = $this->getChildCategoriesQuery();

        return $q->execute();
    }


    /**
     *  Retourne la requête Doctrine permettant de récuperer les sous-catégories
     *      de la catégorie
     *
     * @return Doctrine_Query   requête doctrine
     */
    public function getChildCategoriesQuery()
    {
        return $q = Doctrine_Query::create()
          ->from('IStoreCategory c')
          ->where('c.parent_category_id = ?', $this->getId());
    }

    /**
     *  Retourne tous les articles activés de la catégorie
     *
     * @return Doctrine_Collection  collection d'objet doctrine
     */
    public function getActiveItems()
    {
        return $this->getActiveItemsQuery()->execute();
    }

    /**
     *  Retourne la requête Doctrine permettant de récupérer les articles
     *      activés de la catégorie.
     *
     * @return Doctrine_Query   requête doctrine.
     */
    public function getActiveItemsQuery()
    {
      $q = Doctrine_Query::create()
        ->from('IStoreItem i')
        ->where('i.category_id = ?', $this->getId());

      return Doctrine_Core::getTable('IStoreItem')->addActiveItemsQuery($q);
    }


    /**
     *  Retourne la requête Doctrine permettant de retourner le nombre d'articles
     *      activés dans la catégorie.
     *
     * @return Doctrine_Query   requête doctrine.
     */
    public function countActiveItem()
    {
      $q = Doctrine_Query::create()
        ->from('IStoreItem i')
        ->where('i.category_id = ?', $this->getId());

      return Doctrine_Core::getTable('IStoreItem')->countActiveItems($q);
    }
}
