<?php

/**
 * IStoreBrandTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreBrand');
    }

    /**
     *  Retourne les dernières marques ajoutées.
     *
     * @param <type> $limit
     * @return <type>
     */
    public function getUpdated ($limit = 10)
    {
        $q = $this->createQuery('c')
                ->orderBy('c.created_at')
                ->limit($limit);

        return $q->execute();
    }
}