<?php

/**
 * IStoreOrderLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreOrderLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreOrderLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreOrderLine');
    }
}