<?php

/**
 * IStoreOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreOrder');
    }
}