<?php

/**
 * IStoreCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreCategory');
    }

    /**
     *  Retourne les catégories de premier niveau
     *      Catégories à la racine du catalogue
     */
    public function getFirstLevel ()
    {
        $q = $this->createQuery('c')
                ->where('c.parent_category_id IS NULL');

        return $q->execute();
    }
}