<?php

/**
 * IStoreCreditCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreCreditCardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreCreditCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreCreditCard');
    }


    static public $types = array(
        '1' => 'VISA',
        '2' => 'MasterCard',
        '3' => 'American Express',
        '4' => 'Carte Bleue'
    );

    /**
    *    Retourne le type de carte bancaire
    *
    * @return array()
    */
    public function getTypes()
    {
        return self::$types;
    }
}