<?php

/**
 * IStoreItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreItem');
    }
}