<?php

/**
 * IStoreOrderLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    i-store
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IStoreOrderLine extends BaseIStoreOrderLine
{
    /**
     *  Retourne le prix total de la ligne.
     *      Prix Unitaire * Quantity
     */
    public function getTotalPrice()
    {
        return ($this->getQuantity() * $this->getIStoreItem()->getUnitCost());
    }
}
