<?php

/**
 * IStoreCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreComment');
    }
}