<?php

/**
 * IStoreAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreAddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreAddress');
    }
}