<?php

/**
 * IStoreCreditCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreCreditCardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IStoreCreditCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreCreditCard');
    }
}