<?php

/**
 * IStoreItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    i-store
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IStoreItem extends BaseIStoreItem
{
    /**
     *  Remplace les caractères non ASCII du nom de l'article
     *      par le caractère -
     *
     * @return <type>
     */
    public function getNameSlug()
    {
      return IStore::slugify($this->getName());
    }

    /**
     *  Remplace les caractères non ASCII de la marque de l'article
     *      par le caractère -
     *
     * @return <type>
     */
    public function getBrandSlug()
    {
      return IStore::slugify($this->getIStoreBrand());
    }

    /**
     *  Remplace les caractères non ASCII de la description courte
     *       de l'article par le caractère -
     *
     * @return <type>
     */
    public function getDescriptionSlug()
    {
      return IStore::slugify($this->getShortDescription());
    }
}
