<?php

/**
 * IStoreItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IStoreItemTable extends Doctrine_Table
{
    /**
     *  Retourne le fichier index du moteur Zend Lucene.
     *      Si le fichier n'existe pas, il  crée un nouveau fichier
     *
     * @return file   fichier index de Zend Lucene
     */
    static public function getLuceneIndex()
    {
        ProjectConfiguration::registerZend();

        if (file_exists($index = self::getLuceneIndexFile()))
        {
            return Zend_Search_Lucene::open($index);
        }
        else
        {
            return Zend_Search_Lucene::create($index);
        }
    }

    /**
     *  Retourne le nom du fichier index du moteur de recherche Zend Lucene
     *      stocké dans le répertoire data/ en fonction de l'environnement.
     *
     * @return string     fichier index du moteur de recherche Zend Lucene
     */
    static public function getLuceneIndexFile()
    {
      return sfConfig::get('sf_data_dir').'/item.'.sfConfig::get('sf_environment').'.index';
    }

    /**
     *  Méthode permettant d'executer la requête de recherche dans le
     *      fichier index de Zend Lucene.
     *
     * @param <type> $query     requête de la recherche du client
     * @return <type>
     */
    public function getForLuceneQuery($query)
    {
        // on récupere les résultat de la requête de recherche
        //      dans le fichier index de Zend Lucene
        $hits = self::getLuceneIndex()->find($query);

        // on récupere toutes les clés primaires des articles
        //      inclus dans le résultat
        $pks = array();
        foreach ($hits as $hit)
        {
            $pks[] = $hit->pk;
        }

        // si il y a aucun articles correspondant à la recherche
        //  on renvoie un tableau vide
        if (empty($pks))
        {
            return array();
        }

        // autrement on récupére les articles dans la base de données
        $q = $this->createQuery('i')
        ->whereIn('i.id', $pks)
        ->limit(20);

        $q = $this->addActiveItemsQuery($q);

        return $q->execute();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object IStoreItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IStoreItem');
    }

    /**
     *  Recupere le premier article valide du catalogue.
     *
     * @param Doctrine_Query $q
     * @return <type>
     */
    public function retrieveActiveItem(Doctrine_Query $q)
    {
        return $this->addActiveItemsQuery($q)->fetchOne();
    }

  /**
   *   Retourne les articles valides du catalogue.
   *    La requete peut être ajusté en fonction du besoin.
   *
   * @param Doctrine_Query $q
   * @return <type>
   */
    public function getActiveItems(Doctrine_Query $q = null)
    {
        return $this->addActiveItemsQuery($q)->execute();
    }

  /**
   *   Retourne le nombre d'articles valides dans le catalogue.
   *    La requête peut etre ajusté en fonction du besoin
   *
   * @param Doctrine_Query $q
   * @return <type>
   */
    public function countActiveItems(Doctrine_Query $q = null)
    {
        return $this->addActiveItemsQuery($q)->count();
    }

    /**
     *  Retourne la requete doctrine permettant de récupérer
     *      les articles valides du catalogue. La requete peut
     *      être ajusté en fonction du besoin. Exemple: retourner
     *      les articles valides associés à une catégorie donnée.
     *
     * @param Doctrine_Query $q
     * @return <type>
     */
    public function addActiveItemsQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
          $q = Doctrine_Query::create()
            ->from('IStoreItem i');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.is_activated = ?', true);
//          ->addOrderBy($alias . '.name');

        return $q;
    }

    public function getUpdatedItems ($limit = 10)
    {
        return $this->addUpdatedItemsQuery()->limit($limit)->execute();
    }

    /**
     *  Retourne la requete doctrine permettant de récupérer
     *      les deniers articles mise à jour. La requete peut
     *      être ajusté en fonction du besoin.
     *
     * @param Doctrine_Query $q
     * @return <type>
     */
    public function addUpdatedItemsQuery (Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('IStoreItem i');
        }

        $alias = $q->getRootAlias();


        $q->addOrderBy($alias . '.updated_at DESC');

        return $q;
    }

    public function getNewsItems ($limit = 10)
    {
        return $this->addNewsItemsQuery()->limit($limit)->execute();
    }

    /**
     *  Retourne la requete doctrine permettant de récupérer
     *      les denières nouveautés du catalogue. La requete peut
     *      être ajusté en fonction du besoin.
     *
     * @param Doctrine_Query $q
     * @return <type>
     */
    public function addNewsItemsQuery (Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('IStoreItem i');
        }

        $alias = $q->getRootAlias();
        $q->andWhere($alias . '.is_activated = ?', true);
        $q->addOrderBy($alias . '.created_at DESC');

        return $q;
    }
}