generator:
  class: sfDoctrineGenerator
  param:
    model_class:           IStoreCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          i_store_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des catégories
        display: [ id, name]
      filter:  ~
      form:    ~
      edit:
        title: Modifier la catégorie "%%name%%"
      new:
        title: Ajouter une nouvelle catégorie
