generator:
  class: sfDoctrineGenerator
  param:
    model_class:           IStoreItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          i_store_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:        Gestion des articles
        layout:       stacked
        display:      [name, short_description, unit_cost, is_activated]
        max_per_page: 10
        object_actions:
          _edit:      ~
      filter:  ~
      form:    ~
      edit:
        title: Modifier l'article "%%name%%"
      new:
        title: Ajouter un nouveau article